pdatadir_windows: 'X:\Dammy\mouse_pupillometry\mouse_hf'
pdatadir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/mouse_hf/'
tdatadir_windows: 'H:\data\Dammy'
tdatadir_linux: '/nfs/nhome/live/aonih/data/Dammy'
dirstyle: 'N_D_it'
# os: unix

dates2process:
 - '240116' # fam
 - '240117' # fam
 - '240118' # fam
 - '240119' # fam
 - '240120' # fam
 - '240123' # fam
 - '240123' # fam
 - '240123' # fam
 - '240124' # fam
 - '240124' # fam
 - '240125' # fam
 - '240126' # fam
 - '240126' # fam
 - '240127' # fam
 - '240129' # fam
 - '240129' # fam
 - '240131' # fam
 - '240131' # fam
 - '240206' # fam
 - '240206' # fam
 - '240207' # fam
 - '240208' # fam
 - '240209' # fam
 - '240212' # fam
 - '240212' # fam
 - '240213' # fam
 - '240213' # fam
 - '240214' # fam
 - '240215' # normdev
 - '240215' # normdev
 - '240216' # fam
 - '240219' # fam 10 15 20 25 start of freq switches
 - '240220' # fam 10 15 20 25
 - '240221' # fam 10 15 20 25



protocol: 'fam'
animals2process: ['DO79']
preprocess_pkl: 'DO79_2401_fam_preprocessed_w_suffix.pkl'
#preprocess_pkl_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles/mouse_2309mice_fam_preprocessed.pkl'
pkl_dir_windows: 'X:\Dammy\mouse_pupillometry\pickles'
pkl_dir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles'
do_zscore: true
bandpass_met: [0.1,4]
han_size: 0.15
fs: 90.0
pdata_topic: 'pupildata_2d'
use_TTL: true
pklname_suffix: 'DO79_2401_fam'
sess_to_redo: []
use_canny_ell: false
ow_flag: true