pdatadir: '/nfs/winstor/akrami/mouse_pupillometry/mouse_hf/'
tdatadir: '/nfs/nhome/live/aonih/data/Dammy'
dirstyle: 'N_D_it'
os: unix

dates2process:
 - '221214'
 - '221215'
 - '230116'
 - '230117'
 - '230119'
 - '230214'
 - '230216'
 - '230217'
 - '230221'
 - '230222'
 - '230223'
 - '230224'
 - '230228'
 - '230301'
 - '230303'

protocol: 'fam'
animals2process: ['DO54','DO55','DO56','DO57','DO58']
preprocess_pkl: '/ceph/akrami/Dammy/mouse_pupillometry/pickles/mouse_fam_oldbatch.pkl'
pkl_dir: '/ceph/akrami/Dammy/mouse_pupillometry/pickles'
do_zscore: false
bandpass_met: [0.125,4]
han_size: 0.15
fs: 90.0
pdata_topic: 'pupildata_2d'
use_TTL: true
sess_to_redo: ['']