pdatadir_windows: 'X:\Dammy\mouse_pupillometry\mouse_hf'
pdatadir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/mouse_hf/'
tdatadir_windows: 'H:\data\Dammy'
tdatadir_linux: '/nfs/nhome/live/aonih/data/Dammy'
dirstyle: 'N_D_it'
ceph_dir_linux: '/ceph/akrami'
ceph_dir_windows: 'X:\'
# os: unix

dates2process:
 - '230913' # 76 canny off
 - '230914' # 72 canny off
 - '230915'
 - '230918' # muscimol 1 ul/ul
 - '230919'  # do71 short video 2 vids but not working
 - '230920' # muscimol  76 canny file length different
 - '230926'
 - '230927' # muscimol uni for 75/76
 - '230928' # saline
 - '230929' # muscimol uni for 76
 - '231002' # muscimol fluoro
 - '231023'
 - '231024' # saline
 - '231025'
 - '231027' # saline
 - '231030' # muscimol 0.5uL
 - '231031' # control
 - '231102' # saline. issue with 72. very early event times compared to pupil times
 - '231103' # muscimol 0.5uL
 - '231128' # muscimol
 - '231201' # muscimol
 - '231204' # saline
 - '231206' # muscimol


protocol: 'fam'
animals2process: ['DO71','DO72','DO75']  # 'DO76'
session_topology_path: 'X:\Dammy\Xdetection_mouse_hf_test\session_topology_musc_sept23.csv'
#animals2process: ['DO72',] #  ['DO71','DO72','DO74','DO75','DO76']
# preprocess_pkl: 'mouse_2309mice_fam_preprocessed_w_suffix_240131.pkl'
#preprocess_pkl_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles/mouse_2309mice_fam_preprocessed.pkl'
pkl_dir_windows: 'X:\Dammy\mouse_pupillometry\pickles'
pkl_dir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles'
do_zscore: true
bandpass_met: [0.0,0]
han_size: 0
fs: 90.0
pdata_topic: 'pupildata_2d'
use_TTL: true
pklname_suffix: 'sept23_w_canny_w_new_out_method'
ow_flag: true
use_canny_ell: true
sess_to_redo: []
sess_to_omit: ['DO76']

muscimol_dates:
  - 230918
  - 230920
  - 230927
  - 230929
  - 231002
  - 231128
  - 231206
  - 231030
  - 231103
  - 231201
saline_dates:
  - 230928
  - 231024
  - 231027
  - 231102
  - 231204
none_dates:
  - 230913
  - 230914
  - 230915
  - 231023
  - 231025
  - 231031
