pdatadir_windows: 'X:\Dammy\mouse_pupillometry\mouse_hf'
pdatadir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/mouse_hf/'
tdatadir_windows: 'H:\data\Dammy'
tdatadir_linux: '/nfs/nhome/live/aonih/data/Dammy'
dirstyle: 'N_D_it'
ceph_dir_linux: '/ceph/akrami'
ceph_dir_windows: 'X:\'
# os: unix

dates2process: []


protocol: 'fam'
animals2process: []
# session_topology_path: /ceph/akrami/Dammy/Xdetection_mouse_hf_test/session_topology_musc_2406.csv
session_topology_path: 'X:\Dammy\Xdetection_mouse_hf_test\session_topology_musc_2406.csv'
# preprocess_pkl: 'DO79_2401_fam_preprocessed_w_suffix.pkl'
#preprocess_pkl_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles/mouse_2309mice_fam_preprocessed.pkl'
pkl_dir_windows: 'X:\Dammy\mouse_pupillometry\pickles'
pkl_dir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles'
do_zscore: true
bandpass_met: [0,0]
han_size: 0
fs: 90.0
pdata_topic: 'pupildata_2d'
use_TTL: true
pklname_suffix: 'musc_2406_v2409_walt'
sess_to_redo: []
use_canny_ell: false
ow_flag: false
muscimol_dates:
  - 240627
  - 240703
  - 240709
  # - 240712
  # - 240716
  - 240719
  - 240724
  - 240731
  - 240807
  - 240821
  - 240823
  - 240828
  - 240830
saline_dates:
  - 240626
  - 240702
  - 240705
  # - 240710
  # - 240717
  - 240723
  # - 240726
  - 240730
  - 240802
  - 240806
  - 240809
  - 240820
  - 240822
  - 240827
  - 240829
exclude_dates:
  - 240710
  - 240712
  - 240716
  - 240717
  - 240726
altrand_dates:
  - 240729  # mistake ?
  - 240730
  - 240731
  - 240801
  - 240802
  - 240829
